application: ninth-expanse-88619
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /.*
   script: P3Server.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
